dbt_sqlite:

  target: dev
  outputs:
    dev:
      type: sqlite

      # sqlite locks the whole db on writes so anything > 1 won't help
      threads: 1

      # value is arbitrary
      database: "world-bank-wdi-db/wdi_trade_indicators.db"

      # value of 'schema' must be defined in schema_paths below. in most cases,
      # this should be 'main'
      schema: 'main'

      # connect schemas to paths: at least one of these must be 'main'
      schemas_and_paths:
        main: '/Users/mattdolan/PycharmProjects/world-bank-wdi-db/wdi_trade_indicators.db'

      # directory where all *.db files are attached as schema, using base filename
      # as schema name, and where new schema are created. this can overlap with the dirs of
      # files in schemas_and_paths as long as there's no conflicts.
      schema_directory: '/Users/mattdolan/PycharmProjects/world-bank-wdi-db'

#      # optional: list of file paths of SQLite extensions to load. see README for more details.
#      extensions:
#        - "/path/to/sqlean/crypto.so"
#        - "/path/to/sqlean/math.so"
#        - "/path/to/sqlean/text.so"